[package]
name = "interfaces"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10"
prost = "0.13"
rand = "0.9"
prost-build = "0.13"
chrono = "0.4"

[build-dependencies]
prost-build = "0.13"
chrono = "0.4"
